repos:
  - repo: local
    hooks:
      - id: isort
        name: isort (Python imports sorter)
        entry: isort
        language: python
        types: [python]
        args: ["--profile", "black", "--filter-files"]
  
  - repo: https://github.com/psf/black
    rev: 25.11.0
    hooks:
      - id: black
        name: black (Python Code formatter)
        language: python
  
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        name: flake8 (Python Linter)
        language: python
        args: [--max-line-length=125]
      