repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (Python imports sorted)
        args: ["--profile", "black", "--filter-files"]

  - repo: https://github.com/psf/black
    rev: 26.1.0
    hooks:
      - id: black
        name: black (Python Code formatter)
        language: python
  
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        name: flake8 (Python Linter)
        language: python
        args: [--max-line-length=125]
      